name: Commit and Push Example
on: push
jobs:
  create_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
       - name: Install pytest and flake8
         run: |
          pip install pytest
       - name: Push a file to our repository
         run: |
          pwd
          ls -a 
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" 
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          pytest >> log_pytest.txt
          ls -a
          git add .
          git commit -m "random file from action"
          git push